### ISSUE TITLE
Unittest PR also in this repository?

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jaspAudit#13]
Don is the following PR already in this module?

https://github.com/jasp-stats/jasp-desktop/pull/4225

**Comment by vandenman** [comment]
It's not in there but none of the unit tests are in this module yet. I guess those change will come once we copy all unit tests from jasp-desktop into this repo.

**Comment by AlexanderLyNL** [comment]
Should this remain closed, or should we keep this issue open as a reference?
