### ISSUE TITLE
Replace 'taint' with less technical phrase (e.g. 'relative error')?

### ISSUE THREAD

**Issue by JoKeyser** [jasp-stats/jaspAudit#87]
Hi, I have been trying to figure out a German translation for the concept of 'taint', but so far, without success.
Disclaimer: I am not familiar with financial statistics, I'm just cobbling it together based on searching on the web and accessible books.

My impression is that `taint` is technical jargon for `relative error`. That's at least the closest hint for a German translation I could find so far, coming from Prof. Dr. Irene Rößler und Prof. Dr. Albrecht Ungerer, see page 2 in a PDF on their website, http://www.prof-roessler.de/Dateien/Statistik/monetary-unit-sampling.pdf.
They call it "relativer Fehler", i.e. "relative error":

![jfa-taint](https://user-images.githubusercontent.com/8722846/118977942-0620ed00-b977-11eb-86fd-cb74f83775f8.png)

Maybe you could comment if this an adequate phrase to 1) use it in the German translation, or even 2) replace in the original English strings? (The technical term 'taint' could/should still be mentioned in the help text, of course. Replacing it may also help translation into more languages than just German.)

**Comment by koenderks** [comment]
The taint of an item is best summarized as a "proportional error" I would say, since it is computed as `taint = (book_value - true_value) / book_value. However, it is common in audit terminology to use the term "taint" for this. 

I will take a look at where this can be best replaced in the English strings, then I think weblate will present them to you automatically?

**Comment by JoKeyser** [comment]
@koenderks , thanks for the consideration. I like "proportional error" just as well; maybe it helps for you to decide on a term when you translate into Dutch (or are you using "taint" directly?).
Maybe as a last suggestion: I think it could be useful to include the definition of 'taint' somewhere in the help files, in case it's not already included.

I'll wait for the update on Weblate, so far it seemed to work to update whenever stuff was updated here.

**Comment by koenderks** [comment]
@JoKeyser Thanks for the suggestions! I have included the definition in the help files for each (applicable) analysis. Still need to figure out which strings in the explanatory text to replace.

**Comment by koenderks** [comment]
@JoKeyser Changes to the help files and texts are merged and you will see them pop up in weblate soon enough. Thanks for the suggestions!
